services:
  # dont run backend and front end to run locally
  mongodbserver:
    image: mongo:6.0.17
    container_name: web-shop-mongodb-server
    ports:
      - "27017:27017"
    networks:
      - backend_network

  mariadbserver:
    image: mariadb:11.5.2
    container_name: web-shop-mariadb-server
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
